{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: spacelift-postgres
  labels:
    app: spacelift-postgres
    app.kubernetes.io/part-of: spacelift
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ required "postgres: auth.password is required" .Values.auth.password | quote }}
  POSTGRES_DB: {{ .Values.auth.database | quote }}
{{- end }}
